### ISSUE TITLE
Notifier notification is too small now

### ISSUE THREAD

**Issue by kaiyoma** [barbushin/javascript-errors-notifier#74] opened 2017-09-18 17:02 UTC
Something changed recently with this plugin such that the red box is too small now for its content. Whenever it appears, I can barely see the text and there are horizontal and vertical scrollbars:

![small-error-box](https://user-images.githubusercontent.com/10719780/30554194-aa32dee8-9c71-11e7-83f3-e0a58d8c5ceb.png)

**Comment by barbushin** [comment] 2017-09-20 03:13
Nothing was changed actually. Last update was released in November 2016. Also I can't reproduce it in my browser. Can you check it on some another machine?

**Comment by kaiyoma** [comment] 2017-09-20 14:10
Unfortunately, I don't have access to another machine right now. I'm seeing this problem every time this notifier pops up. Maybe a recent Chrome update caused the change? I'm running Chrome 61.0.3163.91 on Windows 10. I'll try to add more screenshots as I encounter this issue.

**Comment by barbushin** [comment] 2017-09-21 05:44
I'm also using Chrome 61. Try to click on extension popup when it's displayed, and press Ctrl+ `-` and Ctrl + `+` to zoom in/out. Maybe it's just a wrong scale.

**Comment by kaiyoma** [comment] 2017-09-21 14:26
No, that doesn't help. The popup looks the same (scrollbars and obscured text) at all zoom levels.

**Comment by tzikas97** [comment] 2017-09-22 19:54
I was only able to reproduce it when I resized the window to a height of about 150px. The text gets "hidden" because `.buttonsBlock` has `position: fixed;`

![](https://user-images.githubusercontent.com/19753490/30761736-f78d5622-9fe7-11e7-8430-0eb78ccedb66.png)

Note that I have never experienced similar behaviour :smiley:

**Comment by barbushin** [comment] 2017-09-23 00:37
@tzikas97 this is idea of current design - position of this buttons must be fixed :) question is mostly about popup height. We height is so small? I can't reproduce it in Ubuntu.

**Comment by kaiyoma** [comment] 2017-09-25 17:04
I found a public web page that exhibits the issue pretty well: https://www.ifconfig.it/hugo/post/nfd16day1arista/

When I open that page, here's the popup that I see:

![small-popup](https://user-images.githubusercontent.com/10719780/30821060-d38ad6b2-a1d8-11e7-9f36-885c204f6b54.png)

**Comment by barbushin** [comment] 2017-10-24 04:08
Done. It's deployed in 3.1.0 release that will be available in WebStore in 3-4 hours.

**Closed by barbushin** 2017-10-24 04:08 UTC
